In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [7]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a2.ndim

2

In [11]:
a2.dtype

dtype('int32')

In [10]:
a2.itemsize  #since item type is integer

4

In [16]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = np.complex)
a3.itemsize

16

In [17]:
a3

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [14]:
a2.size

9

In [15]:
a2.shape

(3, 3)

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
a2.shape

(3, 3)

In [24]:
a2.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
a2.ravel()  #to flatten the array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a2.min()

1

In [28]:
a2.max()

9

In [29]:
a2.sum()

45

In [30]:
a2.sum(axis = 0)   #addition in columns

array([12, 15, 18])

In [31]:
a2.sum(axis = 1)  #addition in row

array([ 6, 15, 24])

In [33]:
np.sqrt(a2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [34]:
np.std(a2)

2.581988897471611

In [35]:
a2.dot(a2)  #matrix multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])