In [1]:
import numpy as np

In [2]:
n = [1,2,3,4,5,6]  #list
n[1:4]

[2, 3, 4]

In [3]:
n[-1]

6

In [4]:
a = np.array([1,2,3,4,5,6])

In [5]:
a[1:4]

array([2, 3, 4])

In [6]:
a[-1]

6

In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b[1,2]

6

In [11]:
b[:, 2]

array([3, 6, 9])

In [12]:
b[0:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
for i in b:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [15]:
for i in b.flat:
    print(i)

1
2
3
4
5
6
7
8
9


## Sticking two array together

In [16]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a,b

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [17]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [19]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [23]:
res = np.hsplit(a,5)
res

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3],
        [12, 13]]),
 array([[ 4,  5],
        [14, 15]]),
 array([[ 6,  7],
        [16, 17]]),
 array([[ 8,  9],
        [18, 19]])]

In [24]:
res = np.vsplit(a,2)
res

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

## Indexing

In [25]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
b = a >4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [29]:
a[b] = -1 #set num>4 as -1

In [30]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])