### Reference: numpy.pdf

In [3]:
# Lists

a = [1, 3, 5, 7, 9]
b = [2, 4, 6, 8, 10]

c = a + b
print(c)

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]


# Numpy

### Creating Vectors

In [4]:
import numpy as np

a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])
c = a + b
print(c)

print(type(c))

print(c.shape)

[ 3  7 11 15 19]
<class 'numpy.ndarray'>
(5,)


### Creating Matrices

In [5]:
l = [[1, 2, 3], [2, 4, 6], [3, 6, 9]]
a = np.array(l)
print(a)
print(a.shape)
print(a.dtype)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
(3, 3)
int32


In [6]:
m = np.array([[1,2], [3, 4]])
print(m)
print(m.shape)
print(m.dtype)

[[1 2]
 [3 4]]
(2, 2)
int32


In [7]:
m[0,0] = "hello"     # gives error, because array can store only 1 type of data

ValueError: invalid literal for int() with base 10: 'hello'

In [9]:
m[0,0] = 90
print(m)

[[90  2]
 [ 3  4]]


In [10]:
m = np.array([[1, 2], [3, 4]], dtype = complex)
m

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### Accessing Matrices

In [11]:
print(a)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [12]:
print(a[0])
print(a[1, 2])
print(a[1, 1:3])
print(a[:, 1])

[1 2 3]
6
[4 6]
[2 4 6]


In [13]:
a[1,2] = 30
a

array([[ 1,  2,  3],
       [ 2,  4, 30],
       [ 3,  6,  9]])

In [14]:
a[:, 0] = [0, 9, 8]
a

array([[ 0,  2,  3],
       [ 9,  4, 30],
       [ 8,  6,  9]])

### Creating arrays

In [15]:
x = np.arange(0, 10, 1)   # args: start, stop, step
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [17]:
np.logspace(0, 10, 10, base = np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [18]:
# Diagonal matrix

np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
b = np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [20]:
b. dtype

dtype('float64')

In [22]:
n= 1000
intarr = np.zeros(n, dtype = np.int)

print(intarr.shape)
print(intarr.dtype)

(1000,)
int32


In [24]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Array creation and Use

In [25]:
d = np.arange(5)
d

array([0, 1, 2, 3, 4])

In [26]:
d[1] = 9.5
d

array([0, 9, 2, 3, 4])

In [27]:
print(d * 0.5)

[0.  4.5 1.  1.5 2. ]


In [28]:
d = np.arange(5, dtype = np.float)
d

array([0., 1., 2., 3., 4.])

In [29]:
np.arange(3, 7, 0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [30]:
x, y = np.mgrid[0:5, 0:5]
print(x)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [31]:
# Random Data
np.random.rand(5, 5)

array([[0.70225048, 0.28805963, 0.61085597, 0.04559589, 0.25757727],
       [0.50785445, 0.52496625, 0.45104986, 0.52814902, 0.28869037],
       [0.8210683 , 0.07649344, 0.10755806, 0.89820079, 0.22797572],
       [0.58314473, 0.41859315, 0.0224292 , 0.30819799, 0.77951163],
       [0.95835175, 0.09816211, 0.51447896, 0.03550779, 0.47837476]])

### Array Methods

In [32]:
arr = np.arange(10, 20).reshape((2, 5))
print(arr)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [34]:
print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.max())
print(arr.min())

145
14.5
2.8722813232690143
19
10


In [35]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
arr.sort()
print(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]


In [36]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

In [37]:
print(x)

[4.5 2.3 6.7 1.2 1.8 5.5]


In [38]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])
a

array([[1., 2.],
       [4., 3.]])

In [39]:
a.transpose()

array([[1., 4.],
       [2., 3.]])

In [40]:
np.linalg.inv(a)

array([[-0.6,  0.4],
       [ 0.8, -0.2]])

In [41]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [43]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
np.dot(j, j)      # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

### Numpy Statistics

In [44]:
a = np.array([1, 2, 3, 4, 5, 6, 7], float)
np.median(a)

4.0

In [45]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], float)
c = np.corrcoef(a)
c

array([[1., 1.],
       [1., 1.]])

In [46]:
np.cov(a)

array([[1.66666667, 1.66666667],
       [1.66666667, 1.66666667]])